---
- name: install packages apt
  ansible.builtin.apt:
    pkg:
      - net-tools
      - iproute2
      - iptables
      - vim 
      - git
      - bash-completion
      - tar
      - ntp
      - jq
      - ipvsadm
      - apt-transport-https 
      - ca-certificates
      - curl
      - gpg
    state: present 

- name: enable ntp
  ansible.builtin.systemd_service:
    name: ntpd
    state: started
    enabled: true

- name: test Swap
  ansible.builtin.shell: "swapon --show --noheadings | wc -l"
  register: swap_ret

- name: If swap is enabled - disable it
  ansible.builtin.command: swapoff -a
  when: swap_ret.stdout != "0"

- name: Disable SWAP in fstab
  when: swap_ret.stdout != "0"
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s*swap\s*.*)$'
    replace: '# \1'

- name: Install br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Install overlay
  community.general.modprobe:
    name: overlay
    state: present

- name: Load module permanet
  ansible.builtin.copy:
    src: modules-kubernetes.conf
    dest: /etc/modules-load.d/modules-kubernetes.conf
    owner: root
    mode: u=rw,g=r,o=r

- name: Set Sysctl on all nodes
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1

- name: install containerd
  ansible.builtin.include_tasks: containerd.yaml 
